### ISSUE TITLE
Exception in VmImpl

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#368]
We should eliminate all the possible exceptions from VmImpl or wrap them

**Comment by vovapolu** [comment]
For example when we're trying to access to -1 element of an array:

```
java.lang.ArrayIndexOutOfBoundsException: -1 at 
scala.collection.mutable.ResizableArray.update(ResizableArray.scala:49) at
scala.collection.mutable.ResizableArray.update$(ResizableArray.scala:47) at 
scala.collection.mutable.ArrayBuffer.update(ArrayBuffer.scala:48) at 
pravda.vm.operations.HeapOperations.arrayMut(HeapOperations.scala:174) at 
pravda.vm.impl.VmImpl.runBytes(VmImpl.scala:136) at 
pravda.vm.impl.VmImpl.run(VmImpl.scala:84) at pravda.vm.operations.SystemOperations.pcall(SystemOperations.scala:81) at 
pravda.vm.impl.VmImpl.runBytes(VmImpl.scala:176) at 
pravda.vm.impl.VmImpl.spawn(VmImpl.scala:56) at 
pravda.node.servers.Abci.$anonfun$verifyTx$6(Abci.scala:119) at 
scala.util.Try$.apply(Try.scala:209) at 
pravda.node.servers.Abci.$anonfun$verifyTx$5(Abci.scala:119) at 
scala.util.Success.flatMap(Try.scala:247) at 
pravda.node.servers.Abci.$anonfun$verifyTx$3(Abci.scala:118) at 
scala.util.Success.flatMap(Try.scala:247) at pravda.node.servers.Abci.verifyTx(Abci.scala:114) at 
pravda.node.servers.ApiRoute.$anonfun$route$5(ApiRoute.scala:121) at 
akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14) at 
akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:162) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$toStrictEntity$3(BasicDirectives.scala:354) at 
scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303) at 
akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86) at 
scala.concurrent.Future.flatMap(Future.scala:302) at 
scala.concurrent.Future.flatMap$(Future.scala:302) at 
akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$toStrictEntity$2(BasicDirectives.scala:352) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37) at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37) at 
akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:41) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:59) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44) at 
akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44) at 
akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:41) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:41) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47) at 
akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) at 
akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) at 
akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26) at 
akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44) at 
akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65) at 
akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152) at 
akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32) at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:79) at 
akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1189) at 
akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512) at 
akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475) at 
akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371) at 
akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585) at 
akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469) at 
akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560) at 
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742) at 
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757) at akka.actor.Actor.aroundReceive(Actor.scala:517) at 
akka.actor.Actor.aroundReceive$(Actor.scala:515) at 
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667) at 
akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) at 
akka.actor.ActorCell.invoke(ActorCell.scala:496) at 
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) at 
akka.dispatch.Mailbox.run(Mailbox.scala:224) at akka.dispatch.Mailbox.exec(Mailbox.scala:234) at 
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) at 
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) at 
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) at 
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
