### ISSUE TITLE
Pravda broadcast occasionally crashes

### ISSUE THREAD

**Issue by UnimaginaryUnit** [expload/pravda#422]
```bash
lifetimealone@lifetimealone-G5-5587:~/Code/expload/auction/Auction/test$ echo "push 1"| pravda compile asm | pravda broadcast run -w wallets/test-wallet.json -l 9000000 --program-wallet wallets/test-wallet2.json
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'There': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
        at tethys.jackson.JacksonTokenIterator$.fromFreshParser(JacksonTokenIterator.scala:57)
        at tethys.jackson.package$$anon$2.fromReader(package.scala:25)
        at tethys.package$ReaderReaderOps$.readJson$extension(package.scala:47)
        at tethys.package$StringReaderOps$.jsonAs$extension(package.scala:37)
        at pravda.node.data.serialization.TethysInstances.pravda$node$data$serialization$TethysInstances$$$anonfun$tethysJsonDecoder$1(TethysInstances.scala:197)
        at pravda.node.data.serialization.TethysInstances$$anonfun$tethysJsonDecoder$4.apply(TethysInstances.scala:197)
        at pravda.node.data.serialization.TethysInstances$$anonfun$tethysJsonDecoder$4.apply(TethysInstances.scala:197)
        at pravda.node.data.serialization.TranscodingDsl$.to$extension(TranscodingDsl.scala:23)
        at pravda.node.client.impl.NodeLanguageImpl.$anonfun$singAndBroadcastTransaction$7(NodeLanguageImpl.scala:102)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by vovapolu** [comment]
@Chicker was issue resolved?

**Comment by Chicker** [comment]
> @Chicker was issue resolved?

Not sure, @UnimaginaryUnit should confirm or not.

**Comment by UnimaginaryUnit** [comment]
@vovapolu @Chicker yes, seems alright now.

**Comment by UnimaginaryUnit** [comment]
It worked multiple times on sample command provided in issue desc (`echo "push 1"| pravda compile asm | pravda broadcast run...`), but crashes again on my project.

**Comment by UnimaginaryUnit** [comment]
Using Pravda v0.21.0:
```
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'There': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
        at tethys.jackson.JacksonTokenIterator$.fromFreshParser(JacksonTokenIterator.scala:57)
        at tethys.jackson.package$$anon$2.fromReader(package.scala:25)
        at tethys.package$ReaderReaderOps$.readJson$extension(package.scala:47)
        at tethys.package$StringReaderOps$.jsonAs$extension(package.scala:37)
        at pravda.node.data.serialization.TethysInstances.pravda$node$data$serialization$TethysInstances$$$anonfun$tethysJsonDecoder$1(TethysInstances.scala:234)
        at pravda.node.data.serialization.TethysInstances$$anonfun$tethysJsonDecoder$4.apply(TethysInstances.scala:234)
        at pravda.node.data.serialization.TethysInstances$$anonfun$tethysJsonDecoder$4.apply(TethysInstances.scala:234)
        at pravda.node.data.serialization.TranscodingDsl$.to$extension(TranscodingDsl.scala:23)
        at pravda.node.client.impl.NodeLanguageImpl.$anonfun$singAndBroadcastTransaction$7(NodeLanguageImpl.scala:102)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Chicker** [comment]
@UnimaginaryUnit I suppressed noisy stdout messages during startup/shutdown ActorSystem. Check the `0.21.3` version of Pravda. Currently, Pravda CLI commands should not litter in stdout and your output's parser should not be crashed.

**Comment by UnimaginaryUnit** [comment]
@Chicker still having the issue in newer pravda cli versions:
https://ci.dev.expload.com/expload/auction/84

I have 0.21.0 in .csproj files though. May it be the deal here?

**Comment by Chicker** [comment]
> I have 0.21.0 in .csproj files though. May it be the deal here?

@UnimaginaryUnit Yes, definitely. Pravda should be `0.21.3` version where you are calling the Pravda CLI commands

**Comment by vovapolu** [comment]
Same behaviour occurs with other errors, for example when target endpoint is wrong. We should handle json parsing errors more accurate.
