### ISSUE TITLE
Deploy exception

### ISSUE THREAD

**Issue by TrueNoob** [expload/pravda#433]
```
pravda gen address -o wallet.json
// Go to Testnet Faucet to get some XCoin
dotnet publish -c Deploy
```
Exception:
```
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
   at [Source: (StringReader); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
        at tethys.jackson.JacksonTokenIterator$.fromFreshParser(JacksonTokenIterator.scala:57)
        at tethys.jackson.package$$anon$2.fromReader(package.scala:25)
        at tethys.package$ReaderReaderOps$.readJson$extension(package.scala:47)
        at tethys.package$StringReaderOps$.jsonAs$extension(package.scala:37)
        at pravda.node.data.serialization.TethysInstances.pravda$node$data$serialization$TethysInstances$$$anonfun$tethysJsonDecoder$1(TethysInstances.scala:197)
        at pravda.node.data.serialization.TethysInstances$$anonfun$tethysJsonDecoder$4.apply(TethysInstances.scala:197)
        at pravda.node.data.serialization.TethysInstances$$anonfun$tethysJsonDecoder$4.apply(TethysInstances.scala:197)
        at pravda.node.data.serialization.TranscodingDsl$.to$extension(TranscodingDsl.scala:23)
        at pravda.node.client.impl.NodeLanguageImpl.$anonfun$singAndBroadcastTransaction$7(NodeLanguageImpl.scala:102)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by isage** [comment]
Ok, we found out that it's because of forced https.
HelloProgram template uses http (and looks like pravda client by default too)
But pravda client can't handle redirect correctly, thus that exception.
Changing api endpoint to https one fixes this problem.
